import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Your Web3 Community is Waiting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"h-[100vh] min-h-screen bg-slate-600 mono-sans"}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
